development:
  adapter: postgresql
  encoding: unicode
  database: db_web
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: db_web
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: db_web
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin
  host: localhost
