development:
  adapter: postgresql
  encoding: unicode
  database: jhcsjmji
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jhcsjmji
  password: 3j6MLkqNIq5NavCavyxyu6uh7f-NBOaB
  host: peanut.db.elephantsql.com

test:
  adapter: postgresql
  encoding: unicode
  database: jhcsjmji
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jhcsjmji
  password: 3j6MLkqNIq5NavCavyxyu6uh7f-NBOaB
  host: peanut.db.elephantsql.com

production:
  adapter: postgresql
  encoding: unicode
  database: jhcsjmji
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jhcsjmji
  password: 3j6MLkqNIq5NavCavyxyu6uh7f-NBOaB
  host: peanut.db.elephantsql.com
